name: TradeUI
main: me.felnstaren.TradeUI
version: 1.1.6b
author: Felnstaren
description: An easy to use player trading plugin
api-version: 1.14

commands:
 trade:
  aliases: []
  description: TradeUI's main command