name: TradeUI
main: me.felnstaren.TradeMain
version: 0.9.2a
author: Felnstaren
description: A custom, 1 on 1, anti-scam trading plugin.
api-version: 1.14

commands:
 trade:
  aliases: [tr]
  description: Used to send a trade request to someone