#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
#         TRADE UI GENERAL CONFIG         H
#          Plugin by Felnstaren           H
#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH


# What messages do you want to see from this plugin? 
# DEBUG -> INFO -> WARN -> SEVERE
# You will see all messages above the priority you select
logger-priority: INFO


#Set to false to disable trading by using commands
allow-commands: true

#Set to false to disable trading by shift-right-clicking
allow-shifting: true

#Set to false to allow all players to trade
require-trade-permission: true

#Set to -1 to remove the distance requirement
# *Does not allow players in different worlds to trade when set
max-trade-distance: 15

#How long until trades automatically time-out
# *Highly suggested that all trades have a timeout
trade-request-timeout: 20

#Set this to false to not automatically cancel requests if players walk away
cancel-request-on-walk-away: true

#Set this to true to allow players to trade with themselves, Warning: THIS IS A FEATURE PURELY FOR TESTING, the plugin WILL malfunction if you set this to true
allow-self-trading: false